# Generated by Django 5.1.4 on 2024-12-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='rate_to_som',
        ),
        migrations.AddField(
            model_name='currency',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
